# -*- coding: utf-8 -*-
# 生成 lib/app/t2s_chars.g.dart：繁体（含台湾、香港异体字）-> 简体的逐字对照表。
# 只给本地漫画索引做搜索比对的正规化用，不用于显示。
# 来源：OpenCC 的 TSCharacters、TWVariantsRev、HKVariantsRev（多个候选取第一个）。
# 用法：pip install opencc-python-reimplemented && python tools/i18n/gen_t2s.py
import os
import pathlib

import opencc as opencc_pkg

DICT_DIR = pathlib.Path(os.path.dirname(opencc_pkg.__file__)) / 'dictionary'
ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'lib' / 'app' / 't2s_chars.g.dart'


def load(name):
    table = {}
    for line in (DICT_DIR / name).read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or '\t' not in line:
            continue
        key, value = line.split('\t', 1)
        candidates = value.split()
        if len(key) == 1 and candidates and len(candidates[0]) == 1:
            table[key] = candidates[0]
    return table


def bmp(ch):
    return ord(ch) <= 0xFFFF


def main():
    ts = load('TSCharacters.txt')
    variants = {}
    variants.update(load('HKVariantsRev.txt'))
    variants.update(load('TWVariantsRev.txt'))

    mapping = {}
    for trad, simp in ts.items():
        if trad != simp:
            mapping[trad] = simp
    # 异体字先还原成标准繁体，再转简体
    for variant, standard in variants.items():
        simp = ts.get(standard, standard)
        if variant != simp and variant not in mapping:
            mapping[variant] = simp

    # 同时是「简体结果」的字要保持原样（例如 麼→么，但么本身不再转成幺），
    # 否则逐字转一次时「什麼」与「什么」会得到不同结果。
    outputs = set(mapping.values())
    fixed = sorted(k for k in mapping if k in outputs)
    for k in fixed:
        del mapping[k]
    assert not (set(mapping) & set(mapping.values())), '对照表仍有连锁'

    pairs = sorted((k, v) for k, v in mapping.items() if bmp(k) and bmp(v))
    src = ''.join(k for k, _ in pairs)
    dst = ''.join(v for _, v in pairs)
    OUT.write_text(
        '// GENERATED by tools/i18n/gen_t2s.py — do not edit.\n'
        '// 繁体（含台湾、香港异体字）-> 简体逐字对照，只用于搜索比对的正规化。\n'
        '// ignore_for_file: constant_identifier_names\n\n'
        f'/// 共 {len(pairs)} 字，与 [kT2sTo] 逐位对应\n'
        f"const String kT2sFrom = '{src}';\n\n"
        "/// 与 [kT2sFrom] 逐位对应的简体字\n"
        f"const String kT2sTo = '{dst}';\n",
        encoding='utf-8',
        newline='\n',
    )
    print(f'已生成 {OUT}（{len(pairs)} 字；保持原样 {len(fixed)} 字：{"".join(fixed)}）')


if __name__ == '__main__':
    main()
